-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le :  Dim 10 nov. 2019 à 17:39
-- Version du serveur :  10.1.30-MariaDB
-- Version de PHP :  7.2.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `db258477339`
--

-- --------------------------------------------------------

--
-- Structure de la table `ensas_pfe`
--

CREATE TABLE `ensas_pfe` (
  `id` int(10) UNSIGNED NOT NULL,
  `username` varchar(64) NOT NULL,
  `password` varchar(64) NOT NULL,
  `filiere` varchar(64) NOT NULL,
  `groupe` varchar(32) NOT NULL,
  `note` varchar(6) NOT NULL,
  `nom1` varchar(127) NOT NULL,
  `nom2` varchar(127) NOT NULL,
  `nom3` varchar(127) NOT NULL,
  `prenom1` varchar(127) NOT NULL,
  `prenom2` varchar(127) NOT NULL,
  `prenom3` varchar(127) NOT NULL,
  `GSM1` varchar(64) NOT NULL,
  `GSM2` varchar(64) NOT NULL,
  `GSM3` varchar(64) NOT NULL,
  `email1` varchar(127) NOT NULL,
  `email2` varchar(127) NOT NULL,
  `email3` varchar(127) NOT NULL,
  `ville` varchar(127) NOT NULL,
  `sujet` text NOT NULL,
  `descr` text NOT NULL,
  `motscle` text NOT NULL,
  `preembauche` varchar(255) NOT NULL,
  `debut` varchar(255) NOT NULL,
  `duree` varchar(255) NOT NULL,
  `entreprise` text NOT NULL,
  `adresse` text NOT NULL,
  `encadrant` varchar(255) NOT NULL,
  `email_encadrant` varchar(127) NOT NULL,
  `fonction` text NOT NULL,
  `dateconsult` varchar(32) NOT NULL,
  `encadrant_ext` varchar(127) NOT NULL,
  `email_encadrant_ext` varchar(127) NOT NULL,
  `GSM_encadrant_ext` varchar(64) NOT NULL,
  `date` date NOT NULL,
  `heure` time NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `ensas_pfe`
--

INSERT INTO `ensas_pfe` (`id`, `username`, `password`, `filiere`, `groupe`, `note`, `nom1`, `nom2`, `nom3`, `prenom1`, `prenom2`, `prenom3`, `GSM1`, `GSM2`, `GSM3`, `email1`, `email2`, `email3`, `ville`, `sujet`, `descr`, `motscle`, `preembauche`, `debut`, `duree`, `entreprise`, `adresse`, `encadrant`, `email_encadrant`, `fonction`, `dateconsult`, `encadrant_ext`, `email_encadrant_ext`, `GSM_encadrant_ext`, `date`, `heure`) VALUES
(11, 'HaddaneIbtissam', '1234567890', 'T', '06', '15,50', 'HADDANE', '', '', 'Ibtissam ', '', '', '06 22 41 24 37 ', ' ', ' ', 'haddane.ibtissam@gmail.com', '', '', 'Safi', 'DÃ©ploiement d\'une solution d\'interconnexion entre les systÃ¨mes tÃ©lÃ©phoniques analogique et IP : ProblÃ¨me d\'interconnexion sur deux niveaux :entre les systÃ¨mes (analogique et IP) sur le mÃªme site, et entre les sous-sites de l\'OCP Safi. ', '', '', 'non', '', '', 'OCP Safi, Service Informatique ', 'Route Djorf Elyoudi, Safi - BP 219', 'AMMAR', 'ab.ammar@yahoo.fr', 'Chef du Service informatique ', '06/20-17:17', 'KACHOUANI Alaeddine ', '', '', '2015-02-22', '00:00:00'),
(10, 'oussama', 'wecandoit', 'F', '05', '15,50', 'EL GARRAI', '', '', 'Oussama', '', '', '06 40 64 11 36 ', ' ', ' ', 'elgarrai.oussama@gmail.com', '', '', 'Rabat', 'Conception et dÃ©veloppement d\'une application Mobile', 'DÃ©veloppement de lâ€™application mobile ADALA, sous lâ€™environnement Android, et sa mise en ligne sur lâ€™App Store Google pour le compte du MinistÃ¨re de la Justice et des LibertÃ©s.', 'Java, Android, Webservice', 'non', '2015/02/15', '4 mois', 'MinistÃ¨re de la Justice et des LibertÃ©s, DÃ©partement d\'Informatique et de la technologie moderne.', 'site : www.justice.gov.ma', 'OUARRACHI', 'maryam.ouarrachi@gmail.com', 'ingÃ©nieur d\'Ã©tat en informatique', '05/31-01:01', 'SAID NAJAHI', 'sn.najahi@gmail.com', '0600820874', '2015-02-22', '00:00:00'),
(9, 'dounia', '022765032', 'T', '04', '16,00', 'KHIARA', '', '', 'Dounia', '', '', '06 53 08 85 66 ', ' ', ' ', 'douniakhiara2@gmail.com', '', '', 'casablanca', 'Etude et mise en place d\'une solution de supervision du rÃ©seau Ã©tendu de l\'one', '', '', 'non', '15-02-2015', '4 mois', 'L\'one', '65,rue othman ben affan-ex lafuente 20000\r\n\r\nwww.one.org.ma', 'MADIAFI', 'madiafi.med@gmail.com', 'administrateur SAP', '06/01-12:01', 'DAHRAOUI Kamal', 'k.dahraoui@onee.ma ', '0666184641', '2015-02-22', '00:00:00'),
(8, 'REDDAD', 'reddadsaad', 'T', '03', '', 'REDDAD', '', '', 'Saad', '', '', '06 55 57 48 99 ', ' ', ' ', 'saad.reddad@gmail.com', '', '', 'Toulouse', 'SpÃ©cification, implantation et test de mÃ©canismes de gestion de la qualitÃ© de	service dans le middleware	OM2M', '1. DÃ©velopper une comprÃ©hension	de lâ€™internet de objets	de ses applications et	des problÃ©matiques attenantes, notamment en termes	dâ€™architecture.\r\n2. Assimiler la	norme ETSI M2M et les travaux de conception et de dÃ©veloppement ayant conduit Ã  lâ€™implantation de la plateforme OM2M.\r\n3. Assimiler les problÃ©matiques	de gestion de la QoS et	de la scalabilitÃ© dans les intergiciels de type OM2M.\r\n4. SpÃ©cifier, implÃ©menter et intÃ©grer dans la plateforme OM2M, les	mÃ©canismes de gestion de la QoS et de la scalabilitÃ© proposÃ© pour la plateforme.	\r\n5. Tester et valider ces mÃ©canismes sur	la plateforme M2M avec des scÃ©narios d\'expÃ©rimentation Ã  dÃ©finir.	', 'IoT, QoS, ', 'pas dÃ©fini', '01/03/2015', '31/08/2015', 'LAAS-CNRS, Ã©quipe SARA', 'https://www.laas.fr/public/', 'ZYANE', 'a.zyane@yahoo.fr', 'Directeur du DÃ©partement GÃ©nie Electrique et \r\nInformatique (DGEI) de l\'INSA de Toulouse et\r\nChercheur au LAAS/CNRS, Ã©quipe SARA', '06/09-08:10', 'Christophe Chassot', 'christophe.chassot@insa-toulouse.fr ', '', '2015-02-22', '00:00:00'),
(6, 'CHAHID', 'imene123', 'T', '01', '15,23', 'CHAHID', '', '', 'Imene', '', '', '06 10 30 19 47 ', ' ', ' ', 'imene.chahid@gmail.com', '', '', 'SalÃ©', 'La refonte de la plateforme dâ€™authentification  rÃ©seau de Bank EL MAGHRIB', '', 'Authentification, 802.1x, Radius...', 'non', '16/02/2015', '4 mois', 'dar as-sikkah - Bank EL MAGHRIB ', 'Adresse        : Km 8,5 Route de SalÃ© Ã  MekhnÃ¨s - B.P. 445 - RABAT - MAROC\r\nTÃ©lÃ©phone    : + 037 81 80 00\r\n             : + 037 81 81 50\r\nFax             : + 212 37 83 16 41\r\nEmail           : darassikkah@bkam.gov.ma\r\nWeb : http://www.bkam.ma', 'MABTOUL', 'mabtoul_samira@yahoo.fr', 'administrateur systÃ¨me windows', '05/31-02:46', 'Adil AIT BENHADDOU', 'a.aitbenhaddou@bkam.ma', '0637818103', '2015-02-22', '00:00:00'),
(7, 'houdass', 'nana12', 'F', '02', '15,53', 'HOUDASS', 'AINOUSS', 'MYOURI', 'Youness', 'Abdelghani', 'Wissal', '06 45 88 30 92 ', ' ', ' ', 'houd.youness@gmail.com', '', '', 'Casablanca', 'GED (Gestion Ã©lectronique des documents)', '', '', 'pas dÃ©fini', '', '', 'Accolade', 'http://www.accolade-center.com/', 'ATLAS', 'abdelghafour.atlas@gmail.com', 'Chef de projet', '05/29-21:14', 'Said Asmami', 'SASMAMI@accolade.co.ma', '', '2015-02-22', '00:00:00'),
(12, 'amine.faroukhi', 'serious0092', 'F', '07', '15,50', 'FAROUKHI', '', '', 'Amine', '', '', '06 93 27 81 32 ', ' ', ' ', 'amine.faroukhi.af@gmail.com', '', '', 'Casablanca', 'Etude et dÃ©veloppement dâ€™un outil dâ€™aide Ã  la gestion de lâ€™Ã©valuation professionnelle des collaborateurs.', '-systÃ¨me de notation objective par annÃ©e.\r\n-visibilitÃ© de prestations par tÃ¢ches.\r\n-dÃ©cision en terme plan de montÃ©e en compÃ©tence.', '', 'oui', '11/03/2015', '5 mois', 'BNP Paribas MedIT.', 'Casablanca Nearshore Park, 1100 Boulvard Al Qods,Sidi Maarouf 20000 Casablanca.\r\n\r\nhttp://www.bnpparibas-medit.ma/', 'BABALAHCEN', 'babalahcenrajaa@yahoo.fr', 'Project Manager', '06/25-01:30', 'BENNOUR Abdellatif', '', '', '2015-02-22', '00:00:00'),
(13, 'mahdi.bouzarouata@gmail.com', 'ROOTROOT2010', 'F', '08', '14,83', 'BOUZAROUATA', '', '', 'Mahdi', '', '', '06 37 57 48 20 ', ' ', ' ', 'mahdi.bouzarouata@gmail.com', '', '', 'Tetouan', 'Conception et dÃ©veloppement d\'un systÃ¨me de gestion de production ', '', '', 'non', '02/03/2015', '', 'Ghorghiz Cerame', '', 'ELBOUSTANI', 'hakim.el-boustani@orange.fr', 'Chef de production', '06/16-01:41', 'Laghnimi Amine', 'lagh-nimi@hotmail.com', '06 61 52 49 50', '2015-02-22', '00:00:00'),
(14, 'r.zineddine', 'drex123456', 'F', '09', '15,00', 'ZINEDDINE', '', '', 'Reda', '', '', '06 66 26 53 86 ', ' ', ' ', 'zineddine.reda@gmail.com', '', 'zineddine.reda@gmail.com', 'casablanca', 'Mise en place d\'un tableau de bord multifoncitonnelle  ', 'Mise en place d\'un tableau de bord facilitant la lecture et l\'exploitation des donnÃ©es', '', 'non', '08/02/2015', '08/06/2015', 'Structis maroc', 'no', 'CHAHIN', 'radouane.chahin@gmail.com', '', '06/01-22:09', 'BOUZGHIBA Mohammed', 'M.BOUZGHIBA@bouygues-construction.com ', '', '2015-02-22', '00:00:00'),
(15, 'OUTRGA', '123456', 'T', '10', '', 'OUTRGA', '', '', 'Rabia', '', '', '06 50 32 61 00 ', ' ', ' ', 'rabiaoutrga@gmail.com', '', '', 'Rabat', 'Etude des solutions  SDN, avec un cas dâ€™Ã©tude particulier dâ€™ OpenFlow SDN pour simuler et rÃ©pliquer les services TE MPLS', 'Domaine de projet : RÃ©seaux', 'Controleur,, MPLS, SDN, Openfow, Traffic Engineering, ', 'pas dÃ©fini', '2/2/2015', '4 mois', 'CBI', 'TÃ©l : +212 5 37 71 35 55/71 38 75\r\nFax +212 5 37 56 65 56\r\nwww.cbi.ma\r\n', 'ZYANE', 'a.zyane@yahoo.fr', 'Network solutions architect', '05/31-11:41', 'BELYAZIDI Mohamed', 'belyazidi@gmail.com', '0675493034', '2015-02-22', '00:00:00'),
(16, 'Najoua', 'BeauBears357896214', 'F', '11', '15,20', 'BENBAHAKKA', '', '', 'Najoua', '', '', '06 66 31 41 51 ', ' ', ' ', 'benbahakka.najoua@gmail.com', '', '', 'Marrakech', 'RÃ©alisation d\'un ERP pour rÃ©pondre aux besoins des mÃ©tiers des travaux', '', '', 'pas dÃ©fini', '', '', 'SWEDGI', '', 'AMMAR', 'ab.ammar@yahoo.fr', '', '06/11-00:58', 'abdechakour khaioui ', 'k.abdechakour@gmail.com', '', '2015-02-22', '00:00:00'),
(17, 'boutoumilate', '12SpicaVega*', 'F', '12', '15,00', 'BOUTOUMILATE', '', '', 'Dalila', '', '', '06 20 22 04 50 ', ' ', ' ', 'd.boutoumilate@gmail.com', '', '', 'El Jadida', 'DÃ©veloppement d\'un portail collaboratif de gestion des dossiers d\'achat', 'DÃ©velopper un portail collaboratif qui permet de : visualiser lâ€™avancement des dossiers d\'achat depuis le lancement\r\njusqu\'Ã  la concrÃ©tisation,paramÃ©trer le workflow de validation,collaborer avec les acheteurs,archiver les dossiers,construire le tableaux de bord pour faire ressortir le rapport mensuel et les situations des activitÃ©s d\'achat.', 'Workflow,archivage, collaboration, reporting', 'pas dÃ©fini', '04/02/2015', '4 mois', 'Groupe OCP Direction Site de Jorf Lasfar', 'Tel: 05 23 34 52 30 / 05 23 34 50 94\r\nFax : 05 23 34 50 92\r\nSite web : www.ocpgroup.ma', 'ELBOUSTANI', 'hakim.el-boustani@orange.fr', 'Chef de service d\'achat section joint venture', '06/10-00:36', 'M. Abdelhakim BENDAHANE', 'a.bendahane@ocpgroup.ma', '06 61 67 39 96', '2015-02-22', '00:00:00'),
(18, 'h_mekk', 'naruto', 'T', '13', '15,70', 'MEKKAOUI', '', '', 'Houssam', '', '', '06 39 50 39 89 ', ' ', ' ', 'houssam.mekkaoui@gmail.com', '', '', 'Rabat/TÃ©mara', 'DÃ©ploiement de Symantec Data Loss Prevention 12.5', 'Le projet consiste Ã  effectuer le dÃ©ploiement de la partie sÃ©curitÃ© d\'une installation qui vise Ã  mettre en Å“uvre un ensemble de solutions clÃ© en main pour la sÃ©curisation et la protection du systÃ¨me d\'information d\'un client de l\'entreprise dâ€™accueil. Il s\'agit ici d\'un systÃ¨me de Data Loss Prevention 12.5 (DLP) de Symantec.', '', 'pas dÃ©fini', '16/02/2015', '4 mois', 'Axeli S.A.R.L.A.U', 'Avenue Abderrahim Bouabid, Villa A22 CitÃ© Ouhoud - Guich Loudaya - TÃ©mara.\r\nSite : www.axeli.ma', 'CHAHIN', 'radouane.chahin@gmail.com', 'Chef de projet', '06/02-19:33', 'EL KHALFAOUI Latifa', 'latifa.elkhalfaoui@axeli.ma', '0661466580', '2015-02-22', '00:00:00'),
(19, 'elmoromourad', 'mourad123456', 'F', '14', '15,50', 'ELIDRISSI LAHBALI', '', '', 'Mourad', '', '', '06 55 59 75 04 ', ' ', ' ', 'elidrissi.mourad@gmail.com', '', '', 'Rabat', 'Mise en place d\'un systeme de gestion des stagiaires et des CVs sous Wakanda', '', '', 'pas dÃ©fini', '23-fevrier-2015', '', '4D', 'www.4D.com', 'MABTOUL', 'mabtoul_samira@yahoo.fr', 'Chef de service', '05/24-00:38', 'M. Redwane ELHILALI', 'redwan.hilali@4d.com', '06 66 50 32 32', '2015-02-22', '00:00:00'),
(20, 'sara.elkarii', '123456789', 'F', '15', '15,52', 'EL KARII', '', '', 'Sara', '', '', '06 49 98 82 90 ', ' ', ' ', 'elkarii.sara@gmail.com', '', '', 'Rabat', '    La mise en place dâ€™une solution dâ€™aiguillage pour le projet : Frontal de communication entre la direction commerciale (dirCo) et les distributeurs', 'Etude dâ€™impact, DÃ©veloppement, RÃ©daction de cahier de tests, Tests dâ€™intÃ©gration et tests non rÃ©gression', 'GDF, WebMethods, Informatica', 'pas dÃ©fini', 'le 02 mars', '6 mois', 'CGI', 'www.cgi.com', 'ATLAS', 'abdelghafour.atlas@gmail.com', 'Manager', '05/06-11:50', 'Mohammed SAGHROUCHNI', 'mohammed.saghrouchni@cgi.com', '+212 6 62 01 06 61', '2015-02-22', '00:00:00'),
(21, 'meriam', 'zahiraz*123', 'F', '16', '15,35', 'ZAHIRI', '', '', 'Meriam', '', '', '06 18 89 55 90 ', ' ', ' ', 'meriamzahiri@gmail.com', '', '', 'Casablanca', 'Conception et dÃ©veloppement  d\'une application CRM-Mobile ', '', 'android ,EJB3,JPA(Hibernate),WebService,GlassFish,SQL Server2014', 'pas dÃ©fini', '10/02/15', '', 'IMS Technology', '96, Rue Pierre Parent\r\nBureau 28,3eme Ã©tage,20 000-Casablanca\r\nTÃ©l : (+212) 05-22-54-10-18 \r\nFax : (+212) 05-22-44-82-46\r\nwww.ims-technology.ma', 'HEDABOU', 'mhedabou@yahoo.fr', 'Consultant/Formateur informatique', '05/21-20:47', 'Tarik RABEH', 'rabeh@ims-technology.ma', '+212 614759278', '2015-02-22', '00:00:00'),
*(22, 'laila', 'lolla123', 'F', '17', '15,00', 'BOUTOR', 'LAAROUA', '', 'Laila', 'Abdeladim', '', '06 29 45 10 54 ', '06 70 88 98 98 ', ' ', 'l.boutor@gmail.com', 'abdeladim.laaroua@gmail.com', '', 'Casablanca', 'DÃ©veloppement et mise en place d\'un progiciel de gestion intÃ©grÃ© (ERP)', '', '', 'pas dÃ©fini', '', '', '', '', 'JRAIFI', 'jraifi.abdelilah@gmail.com', '', '05/28-10:06', '', '', '', '2015-02-22', '00:00:00'),
*(23, 'lakhsam', 'fatimarhazi1991', 'F', '18', '14,94', 'LAKHSAM', '', '', 'Ahmed', '', '', '06 70 99 90 89 ', ' ', ' ', 'ahmed.lakhsam@gmail.com', '', '', 'San Sebastian', 'La dÃ©tection des objets (comme toiture, route, vÃ©gÃ©tation etc) dans des images aÃ©riennes .', '', 'la dÃ©tection automatique du bÃ¢timent et de dÃ©limitation; Orthophotos ;segmentation de l\'image ; descripteurs de l\'image; L\'apprentissage supervisÃ©; Classificateur;', 'non', '02-03-2015', '3 mois ou plus ', 'Lâ€™universitÃ© du Pays basque ,La facultÃ© de l\'informatique', 'Manuel Lardizabal Pasealekua, 1 - 20018 \r\nDonostia-San SebastiÃ¡n\r\nTel: 943 015245 Fax: 943 015590\r\ninfo-dif-fiss@ehu.es\r\nhttp://www.ehu.eus/eu/web/informatika-fakultatea', 'ECH-CHADI', 'saidech@gmail.com', 'Professeur / Professeur  ', '05/21-09:30', 'Pr. MOUJAHID Abdelmalik(1) et Pr. DORNAIKA Fadi (2)', 'jibmomoa@gmail.com / fadi.dornaika@ehu.es,', '+34 943015698', '2015-02-22', '00:00:00'),
(24, 'Zhour', 'sanazhour', 'T', '19', '14,05', 'FATHI', '', '', 'Zhour', '', '', '06 15 54 18 27 ', ' ', ' ', 'zhour90fathi@gmail.com', '', '', 'Casablanca', 'Etude  de faisabilitÃ© et mise en place d\'un nouveau service de messagerie Office 365 Ã  l\'OCP Casablanca ', 'Dans ce projet au sien de l\'Ocp Casablanca on veut faire une Ã©tude et planification de la nouvelle technologie de messagerie office 365 (version Cloud) en gÃ©nÃ©rale et le service Exchange 365 en particulier. Le Group ocp vise Ã  migrer vers la version cloud pour minimiser le cout, faciliter la gestion des donnÃ©es, et profiter de la sÃ©curitÃ© requise.', '', 'non', '01-04-2015', '4 mois', 'office chÃ©rifien des phosphates siÃ¨ge', 'http://www.ocpgroup.ma/', 'JRAIFI', 'jraifi.abdelilah@gmail.com', '', '06/23-16:33', 'EL Aouni Abdelmounaim', 'Abdelmounaim.elaouni@ocpgroup.ma', '0666635083', '2015-02-22', '00:00:00'),
*(25, 'salma.benaabd', 'Deux+deux=5', 'F', '20', '15,23', 'BENAABD', '', '', 'Salma', '', '', '06 70 98 04 69 ', ' ', ' ', 'salma.benaabd@gmail.com', '', '', 'Rabat', 'Mise en place d\'une application web de gestion des astreintes', 'La conception et la rÃ©alisation d\'une application web pour gÃ©rer les astreintes au sein de ATOS-Rabat.', 'Conception-Developpement-Application-Web-gestion-Astreinte-JEE-Spring-Mysql', 'pas dÃ©fini', '23/02/2015', '23 semaines', 'ATOS', 'Avenue Annakhil\r\nEspace High Tech Hall B â€“ 5Ã¨me Ã©tage\r\nHay Ryad â€“ Rabat\r\nMorocco\r\n\r\nTel: 00 212 (0) 37 57 79 79\r\nFax: 00 212 (0) 37 71 55 59\r\nWeb : www.atos.net/', 'OUAFIK', 'youafik@yahoo.fr', 'Directeur de projet', '06/03-12:41', 'Mohamed Halim SBAA', '', '', '2015-02-22', '00:00:00'),
*(26, 'Arrafi', 'amounti@51', 'F', '21', '16,00', 'ARRAFI', '', '', 'Imane', '', '', '06 16 46 59 84 ', ' ', ' ', 'imane.arrafi@gmail.com', '', '', 'Casablanca', 'DÃ©veloppement d\'une solution BI pour l\'intÃ©gration des donnÃ©es vas/ussd', '- DÃ©veloppement d\'un ETL de bout en bout \r\n- Design d\'un entrepÃ´t de donnÃ©es\r\n- DÃ©veloppement d\'un univers sous BO ', 'BI,ETL,BO', 'pas dÃ©fini', '16 FÃ©vrier 2015', '4 mois', 'dÃ©partment qualitÃ© end to end -INWI', 'http://www.inwi.ma/', 'ELBOUSTANI', 'hakim.el-boustani@orange.fr', 'Chef de projet outils qualitÃ©', '06/24-16:20', 'Mme. Andjar Khaoula ', '', '', '2015-02-23', '00:00:00'),
(27, 'sanae', '@nadati@0619', 'T', '22', '', 'EL YOUSFI', '', '', 'Sanae', '', '', '06 58 33 27 59 ', ' ', ' ', 'elyousfi.sanae@gmail.com', '', '', 'Toulouse', 'Provisionnement de rÃ©seaux virtuels applicatifs : Application Ã  la simulation distribuÃ©e', '', '', 'pas dÃ©fini', '01/03/2015', '6 mois', '', '', 'ZYANE', 'a.zyane@yahoo.fr', 'chercheurs ', '06/09-09:17', 'Slim Abdellatif  et Pascal Berthou ', 'slim@laas.fr  / berthou@laas.fr', '', '2015-02-23', '00:00:00'),
(28, 'mutaz', 'mutazghanem', 'T', '23', '15,06', 'GHANEM', '', '', 'Mutaz', '', '', '06 42 91 64 73 ', ' ', ' ', 'mutaz.ghanem@gmail.com', '', '', 'Casablanca', 'Mise en place des politiques de sÃ©curitÃ© des systÃ¨mes d\'information au sein de l\'entreprise SisPay', '1-mise en place de solustions de sÃ©curisation les serveurs SISPAY en France et Canada (OVH,GIGAPRO)\r\npour les donnes et les comptes des clients Sispay(stations,hotels,restaurants,HP,....).\r\n\r\n2-mise en place de solustions de securisation les serveurs internes pour l\'entreprise SISPAY et monitoring PCs par les bandwidth consommes des employÃ©s et les clients\r\n3-Superviser les serveur internes et les extÃ©rieur par nagios.', 'pfsense firewall,ASA firewall , VPN,Threat detection ,Monitoring,network,portial captive,system(Centos),nagios', 'pas dÃ©fini', '09/02/2015', '4 mois', 'SISPAY-Service Support', 'http://sispay.net/', 'MABTOUL', 'mabtoul_samira@yahoo.fr', 'Support and Quality', '05/30-18:39', 'RAIS Mustapha', 'mostafa.rais@sispay.net', '', '2015-02-23', '00:00:00'),
*(29, 'BOURHI', 'Solitair123$$', 'F', '24', '16,00', 'BOURHI', 'ELALAOUI', '', 'Maryem', 'Sara', '', '06 35 38 84 05 ', '06 68 09 35 80 ', ' ', 'm.bourhi@gmail.com', 'sara.elalaoui92@gmail.com', '', 'Casablanca', 'DÃ©veloppement dâ€™une Appexchange d\'automatisation de gestion des versions sous Salesforce.com', 'Une solution de gestion d\'intÃ©gration continue permettant de : \r\n      -Comparer et synchroniser les diffÃ©rentes instances du mÃªme environnement Salesforce. \r\n      -Faciliter les tÃ¢ches de dÃ©ploiement.\r\n      -Faire des retours en arriÃ¨res de Metadata sÃ©curisÃ©s.\r\n      -DÃ©ploiement de Metadata entre les Organisations Salesforce.\r\n      -Minimiser les interventions manuelles.\r\n      -AmÃ©liorer la collaboration entre les dÃ©veloppeurs.\r\n', 'Salesforce.com, intÃ©gration continue, metadata api, tooling api, Soap api,Versionning', 'oui', '01/02/2015', '6 mois', 'Kerensen Consulting', 'http://www.kerensen.com/', 'ATLAS', 'abdelghafour.atlas@gmail.com', 'Senior Consultant CRM/Consultant CRM', '05/28-18:06', 'Youssef ELQANDILI / Jamal RIDA', 'youssef.elqandili@kerensen.com, jamal.rida@kerensen.com', '+ 212 (5) 22 42 36 40/+ 212 (5) 22 42 36 50', '2015-02-23', '00:00:00'),
*(30, 'chemseddine', 'raja+realmadride', 'F', '25', '16,00', 'ELGARRAI', '', '', 'Chemseddine', '', '', '06 67 05 43 62 ', ' ', ' ', 'chemseddine123@gmail.com', '', '', 'casablanca', 'dÃ©veloppement d\'une plateforme de gÃ©olocalisation et gestion de flotte', 'DÃ©veloppement  d\'une application de gÃ©olocalisation et de traÃ§abilitÃ© des vÃ©hicules et la gestion de flotte : \r\napplication mobile : IOS,objectif c,google api,web service avec c sharp\r\nplateforme web : Asp.net,EXT,google api,web service avec c sharp (participation au DÃ©veloppement)', 'gÃ©olocalisation, flotte ', 'pas dÃ©fini', '18/02/2015', '4 mois', 'GEOMTEC', 'geomtec.com', 'BOUARIFI', 'walid.bouarifi@gmail.com', 'Chef technique', '06/03-17:04', 'HRIFECH Abdelouahid', 'hrifechabdelouahid@gmail.com', '0611503403', '2015-02-23', '00:00:00'),
(31, 'MAAIFI', 'Dragonsoul01', 'T', '26', '15,75', 'MAAIFI', '', '', 'Anas', '', '', '06 14 15 99 27 ', ' ', ' ', 'maaifi.anas@gmail.com', '', '', 'Marrakech', 'Optimisation Data (Etude de l\'architecture Smart Capacity)', 'Nouvelle solution en cours de dÃ©ploiement Ã  WANA CORP (Inwi) en collaboration avec le fournisseur Citrix', '', 'pas dÃ©fini', '02/02/2015', '30/05/2015', 'STE WANA CORPORATE (INWI)', '371 SEC SECTEUR PROVISOIRE QTI INDUSTRIEL SIDI GHANEM\r\n40000 Marrakech', 'BARAKA', 'baraka.kamal@yahoo.fr', 'Responsable DATA', '05/30-17:30', 'RACHAM Younes', 'Younes.Racham@inwi.ma', '0600001350', '2015-02-23', '00:00:00'),
*(32, 'ETTARBAOUI', '123', 'F', '27', '15,14', 'ETTARBAOUI', 'MERSOUL', '', 'Ayoub', 'Abdelhadi', '', '06 45 78 30 31 ', '06 44 75 27 64 ', ' ', 'ettarbaoui.ayoub@gmail.com', 'abdelhadimersoul@gmail.com', '', 'Casablanca', 'Mise en place d\'une plateforme de Tracking de marchandise et DÃ©veloppement du site web de la sociÃ©tÃ©', '', 'JEE, Spring MVC, JSTL, Hibernate, Mysql, PHP, Symphony, HTML5, CSS3', 'pas dÃ©fini', '19 FÃ©vrier 2015', '6 mois', 'Winconnect', '35 Rue de la Dordogne,lagironde Casablanca', 'HEDABOU', 'mhedabou@yahoo.fr', 'Co-fondateur', '06/23-15:14', 'Mohamed Touzani', 'touzani@winconnect.ma', '', '2015-02-23', '00:00:00'),
*(33, 'khaoulaelmessari', 'dieumerci@', 'F', '28', '15,07', 'EL MESSARI', '', '', 'Khaoula', '', '', '06 70 12 74 56 ', ' ', ' ', 'khaoulaelmessari@gmail.com', '', '', 'Rabat ', 'Mise en place d\'une solution dÃ©cisionnelle permettant  l\'exploitation d\'un datawarehouse basÃ©e sur une Ã©tude benchmarking des outils BI.', ' Le but de stage est de rÃ©aliser une Ã©tude comparative des outils dÃ©cisionnels permettant l\'exploitation d\'un Datawarehouse et puis plusieurs critÃ¨res de choix seront Ã  dÃ©finir et Ã  tester sur une plateforme dÃ©cisionnelle.', '', 'pas dÃ©fini', '09/02/2015', '4 mois', 'Ingenius Information technology and Security ', 'Adresse du siÃ¨ge social: \r\n63 AVENUE MOHAMED VI (EX JOHN KENNEDY)- RABAT\r\nAdresse web:http://www.ingenius.ma/ \r\n \r\nTÃ©l. :       +212 5 37 65 99 01\r\n               +212 5 37 75 33 92\r\n               +212 5 37 75 33 99\r\nFax :       +212 5 37 65 60 76', 'OUARRACHI', 'maryam.ouarrachi@gmail.com', 'Chef de projet BI\r\n', '05/27-16:55', 'SEDRAOUI Nawfal', 'nawfal.sedraoui@ingenius.ma', '0662082689', '2015-02-23', '00:00:00'),
*(34, 'brsSculptor', 'PÂ¨M./Â§%ÂµÂ¨Â£', 'F', '29', '15,30', 'BENAISS', 'BOUHTICH', '', 'Youssef', 'Ayoub', '', '06 42 52 40 18 ', '06 33 73 91 08 ', ' ', 'benaiss.youssef@gmail.com', 'ayb01.bh@gmail.com', '', ' SalÃ©', 'Etude et amÃ©lioration de la plateforme de gÃ©nÃ©ration de code Sculptor.', 'Le but est d\'Ã©tudier et de faire Ã©voluer une plateforme de gÃ©nÃ©ration de code selon le concept MDA, Sculptor. Ensuite, il dÃ©veloppera Ã  l\'aide de cette plateforme, une application pour gÃ©rer une plateforme de paiement multi services.', 'Sculptor, MDA, EDA, DSL, xtext, xtend, xpand, Spring, spring integration, camel, Hibernate, jenkins, sonar, Primefaces, Oracle, MySql.', 'pas dÃ©fini', '16-02-2015', '', 'Business Rules Solutions S.A.R.L', 'Av. Lalla Asmaa, Lot. HAJJIA IMB 7, 3Ã¨me Ã©tage Appt 6\r\nQuartier Tabriquet\r\nwww.brs.ma', 'OUAFIK', 'youafik@yahoo.fr', 'Directeur Technique\r\n', '06/27-15:35', 'Mustapha RACHID,Mhammed TEMRI', 'm.rachid@brs.ma,mtemri@gmail.com', '00 212 537 85 33 95', '2015-02-23', '00:00:00'),
*(35, 'ELJANATI', 'eljanati123', 'F', '30', '15,16', 'EL JANATI', '', '', 'Salma', '', '', '06 73 15 31 71 ', ' ', ' ', 'eljanati.salma@gmail.com', '', '', 'Casablanca', 'RÃ©alisation dâ€™une Solution de Reporting RÃ©glementaire Bancaire', '   RÃ©alisation dâ€™une solution de Reporting RÃ©glementaire spÃ©cifique Ã  la Veille sectorielle pour les Ã©tablissements de crÃ©dit et sociÃ©tÃ© de financement.  ', '', 'pas dÃ©fini', '2/02/2015', '4 mois', 'OMNITADA Casablanca', '', 'ECH-CHADI', 'saidech@gmail.com', 'Consultant senior BI', '05/30-19:14', 'TADLAOUI Tarik', 'Ttadlaoui@omnidata.ma', '+212 (0) 522 77 56 00', '2015-02-23', '00:00:00'),
(36, 'Omar', 'p@ssw0rdm', 'T', '31', '16,00', 'BOURAKKADI HASSANI', '', '', 'Omar', '', '', '06 71 77 62 73 ', ' ', ' ', 'omar.bourakkadi@gmail.com', '', '', 'SalÃ©', 'Wi-Fi Offload Alcatel-Lucent : Etude de lâ€™architecture et de lâ€™intÃ©gration dans le rÃ©seau Back Bone IP/MPLS.', ' Axes du projet :\r\n- IntÃ©gration WlanGw 7750SR avec OCS.\r\n- Authentification AAA/HLR .\r\n- SÃ©curitÃ© Firewall Fortinet.\r\n- IntÃ©gration IP/MPLS.', 'MPLS,AAA,3G/4G,Firewall,OCS', 'non', '09/02/2015', '31/05/2015', 'Alcatel-Lucent MAROC', ' Route de MeknÃ¨s, km 8 - 11000  SalÃ©\r\nwww.alcatel-lucent.com', 'BARAKA', 'baraka.kamal@yahoo.fr', 'Program Manager', '06/01-17:31', '  Elmahdi MAJID ALAOUI', '', '', '2015-02-23', '00:00:00'),
*(37, 'nabilox', 'nabilOX2001', 'F', '32', '14,70', 'HARAKAT', '', '', 'Nabil', '', '', '06 75 65 79 74 ', ' ', ' ', 'harakat.nabilox@gmail.com', '', '', 'casablanca', 'Conception et mise en place dâ€™un systÃ¨me de signature Ã©lectronique pour la sÃ©curisation des transactions', '', 'gestion des fichiers logs, active directory, pki, signature des fichiers', 'non', '04/02/2015', '04/06/2015', 'oxyliom', 'http://oxyliom.com', 'CHAHIN', 'radouane.chahin@gmail.com', 'General Manager', '06/13-12:20', 'Anwar EL BARAKA', 'anwar.elbaraka@nexusgroup.com', '0661606597', '2015-02-23', '00:00:00'),
(38, 'HIBOUR', 'ramalama@@', 'T', '33', '15,50', 'HIBOUR', '', '', 'Meryem', '', '', '06 75 36 04 49 ', ' ', ' ', 'meryem.hibour@gmail.com', '', '', 'SAFI', 'Dimensionnement et planification de la gÃ©nÃ©ralisation du rÃ©seau WIFI OCP ', '', '', 'pas dÃ©fini', '', '', 'OCP SAFI\r\nDepartement informatique', '', 'BARAKA', 'baraka.kamal@yahoo.fr', 'Chef du dÃ©partement informatique', '05/31-00:14', 'M.KECHOUANI', '', '', '2015-02-23', '00:00:00'),
(39, 'benzakour-mouad', '1991', 'T', '34', '16,00', 'BENZAKOUR', '', '', 'Mouad', '', '', '06 41 27 21 07 ', ' ', ' ', 'benzakourmouad1991@gmail.com', '', '', 'casablanca', 'Conception et implÃ©mentation d\'une Iaas avec OPENSTACK et EMC NETWORKER', '- Conception et implÃ©mentation d\'une Iaas avec OPENSTACK\r\n- integration de la solution de stockage EMC NETWORKER', '', 'pas dÃ©fini', '02/03/2015', '3 mois', 'CNSS (La Caisse Nationale de SÃ©curitÃ© Sociale)\r\ndÃ©partement SI (systÃ¨me d\'information)', '649 Boulevard Mohamed V, Casablanca, Maroc\r\nsite:http://www.cnss.ma/', 'LAKHEL', 'lakhel@yahoo.fr,lakhel@ucam.ac.ma', 'Chef de service', '06/24-08:21', 'MAACHOU Ahmed', '', '0660117016', '2015-02-23', '00:00:00'),
*(40, 'sekkah', 'qsdcxw', 'F', '35', '15,72', 'SEKKAH', '', '', 'Outmane', '', '', '06 10 15 95 34 ', ' ', ' ', 'outmane.sekkah1@gmail.com', '', '', 'Casablanca', 'RÃ©alisation et mise en place d\'une plateforme Ã©lectronique de ventes aux enchÃ¨res.', 'Le projet est la rÃ©alisation et la mise en place de la 1Ã¨re plateforme des ventes aux enchÃ¨res au Maroc.', 'Java, JEE, Vaadin, Spring, JPA-Hibernate, UP-XP, UML', 'pas dÃ©fini', '23-02-2015', '6', 'iDills', 'http://www.idills.net', 'HEDABOU', 'mhedabou@yahoo.fr', 'Chef de projet', '06/15-13:56', 'M. Zakaria BENTAHAR ', 'contact@idills.net', '0522780909', '2015-02-23', '00:00:00'),
(41, 'loubna', 'loubna', 'T', '36', '14,10', 'MIRI', '', '', 'Loubna', '', '', '06 42 12 26 92 ', ' ', ' ', 'miri.loubna@gmail.com', '', '', 'casablanca ', 'Etude fondamental du rÃ©seau MPLS', 'faire une Ã©tude sur le rÃ©seau MPLS ( liaisons principales ) et superviser des liens de secours RNIS en implÃ©mentant une application Java', 'RNIS , MPLS , JAVA ', 'pas dÃ©fini', '20/02/2015', '3mois 10jrs', 'CBI : Producteur de productivitÃ© \r\nCDS : centre de service \r\n\r\n', 'www.cbi.ma/\r\nImm CBI ; 29/30;lot.Attaoufik;Sidi Maarouf;20270 casablanca', 'JRAIFI', 'jraifi.abdelilah@gmail.com', 'Responsable technique CDS //ingÃ©nieur systÃ¨mes et rÃ©seaux', '05/28-11:14', 'le 1er encadrant : Nour-Eddine DAHER //2eme encadrant :Rachid RACHIDI ', 'ndaher@cbi.ma //r.rachidi@cbi.ma', '0663716960 // ', '2015-02-23', '00:00:00'),
(42, 'ridagtr', '123456', 'T', '37', '', 'ETTAYEA', '', '', 'Rida', '', '', '06 51 96 96 35 ', '06 01 44 78 24 ', ' ', 'ridaettayea@gmail.com', '', '', 'Casa', 'Adminstrateur et Supervision des Switch', '', 'protocole SNMP, Outil de sepurvision nagios et centreon ', 'pas dÃ©fini', '12/02', '4 mois', 'RICHBOND / DÃ©partement Informatique', 'Km 11.7 Km Autoroute Casa-Rabat\r\nwww.richbond.ma\r\nwww.grouperichbond.ma \r\n', 'BENLAMKADEM', 'benlamkadem@gmail.com', 'Responsable SÃ©curitÃ© et RÃ©seau Informatique', '05/30-17:57', 'Fajr Youssef El Idrissi', 'yfajr@richbond.ma', '0679823817', '2015-02-23', '00:00:00'),
*(43, 'adilbarrak', 'adilokas', 'F', '38', '14,08', 'BARRAK', '', '', 'Adil', '', '', '06 51 87 85 36 ', ' ', ' ', 'adil.barrak@gmail.com', '', '', 'Casablanca', 'Conception et RÃ©alisation  Back office de Rekrute', '', '', 'non', '16/02/2015', '15/06/2015', 'Rekrute , dÃ©partement Informatique', '', 'OUARRACHI', 'maryam.ouarrachi@gmail.com', 'dÃ©veloppeur', '05/31-01:35', 'Kaaouachi youssef', 'adil.barrak@gmail.com', '0677159776', '2015-02-23', '00:00:00'),
(44, 'khawla', 'laamima', 'T', '39', '15,45', 'LAAMIMA', '', '', 'Khawla', '', '', '06 01 16 83 08 ', ' ', ' ', 'laamima.khawla@gmail.com', '', '', 'Casablanca', 'Mise en place d\'une politique de sÃ©curitÃ© basÃ©e sur un audit contre les attaques rÃ©seaux', 'Analyse de la politique de sÃ©curitÃ© existante\r\nAnalyse des attaques visant les Ã©quipements rÃ©seaux \r\naudit de sÃ©curitÃ©\r\nMÃ©thode d\'analyse des menaces/vulnÃ©rabilitÃ©s', 'politique de sÃ©curitÃ© , audit de sÃ©curitÃ© , mÃ©thode d\'analyse des risques , standard de sÃ©curitÃ©', 'non', 'Du 16/02/2015 Au 16/06/2015', '4 mois', 'La direction de la mÃ©tÃ©orologie nationale', 'Maroc MÃ©tÃ©o - AÃ©roport Casa-Anfa, Face PrÃ©fecture Hay Hassani - B.P. 8106 Casa Oasis - Casablanca - Maroc\r\ncontact@marocmeteo.ma', 'LAKHEL', 'lakhel@yahoo.fr,lakhel@ucam.ac.ma', 'Administrateur rÃ©seaux', '05/05-20:03', 'Mohamed EL HAITI', 'mohaiti@gmail.com', '0614322002', '2015-02-23', '00:00:00'),
*(46, 'BOUCHAMA', 'passwordpfe', 'F', '41', '15,52', 'BOUCHAMA', '', '', 'Wissal', '', '', '06 58 82 89 13 ', ' ', ' ', 'wissalbouchama@gmail.com', '', '', 'Casablanca', 'RÃ©alisation dâ€™une solution Client LÃ©ger Riche', '', '', 'pas dÃ©fini', '09-03-2015', '31-08-2015', 'EBC System Morocco', '', 'BOUARIFI', 'walid.bouarifi@gmail.com', 'ingÃ©nieur', '06/14-14:08', 'Omar OUALLA', 'omar.oualla@ebcsystem.ma', '0522951405', '2015-02-23', '00:00:00'),
(47, 'maria', 'moimaria123', 'T', '42', '', 'BEN-HACHEM', '', '', 'Maria', '', '', '06 06 09 41 15 ', ' ', ' ', 'maria.benhachem@gmail.com', '', '', 'casablanca', 'Ã©tude et mise en service de la solution IP-RAN de Alcatel au compte de  Maroc-Telecom', '', 'GSM ; UMTS; RAN ; ATM ; DTM ; IP ; Ethernet ; IP-RAN ; VPN ;BGP ;IGP; MPLS', 'pas dÃ©fini', '09/02/2015', '4 mois', 'SIRECOM(SociÃ©tÃ© d\'IngÃ©nierie et RÃ©seaux de TÃ©lÃ©communication )', 'N 8 Lotissement Bab El Kheir Z.I Lissasfa Casablanca-Maroc', 'BENLAMKADEM', 'benlamkadem@gmail.com', 'IP project Manager', '06/12-13:23', 'MOUAKKID Hind ', 'hind.mouakkid@sirecom.ma', '0522932979 - 0661066572', '2015-02-23', '00:00:00'),
(48, 'OUZAYD', 'ouzaydabdessamad', 'T', '43', '14,62', 'OUZAYD', '', '', 'Abdessamad', '', '', '06 36 03 68 09 ', ' ', ' ', 'abdessamad.ouzayd@gmail.com', '', '', 'Tanger', 'IntÃ©gration de GTC (Gestion Technique CentralisÃ©e) dâ€™un Datacenter en une application Web', 'permettre une portabilitÃ© Ã  la solution GTC, mieux dit, aprÃ¨s sa finalisation nous pouvons avoir un accÃ¨s Ã  distance pour visualiser les Ã©tats des composant Datacenter (Clims, onduleurs, G.E. â€¦), et comme Ã§a permettre une rÃ©activitÃ© optimale en cas des incidents. ', 'php,rslinx', 'pas dÃ©fini', '06 avril 2015', '05 aout 2015', 'CIRES TELECOM', 'Zone franche de Ksar El Majaz, Oued Râ€™mel', 'MABTOUL', 'mabtoul_samira@yahoo.fr', 'Datacenter Administrator', '06/01-19:09', 'Dr. EL AMIN AOULAD ABDELOUARIT', 'm.eljabri@cirestelecom.ma', '+212 (0) 5 39 33 70 34', '2015-02-23', '00:00:00'),
(49, 'ennaouiouazzani', 'oncfrabat', 'T', '44', '16,00', 'ENNAOUI', 'HOUSSAM OUAZZANI', '', 'Fatim zahra', 'Hanan', '', '06 33 45 09 82 ', '06 97 03 14 32 ', ' ', 'fatimzahraennaoui@gmail.com', 'h.hanan.ouazzani@gmail.com', '', 'Rabat', 'synchronisation du rÃ©seau de transmission SDH de l\'ONCF', 'le rÃ©seau SDH de l\'ONCF est synchronisÃ© par une horloge interne d\'un Ã©quipement SDH qui a une prÃ©cision de 10-7, le rÃ©seau devient de plus en plus Ã©tendu donc cette prÃ©cision prÃ©sente des limitations de fiabilitÃ©, donc on doit synchroniser le rÃ©seau Ã  une horloge qui a une prÃ©cision plus Ã©levÃ©e.', 'synchronisation, SDH, PRC, SSU,SEC', 'non', '16/02/2015', '31/05/2015', 'oncf de Rabat', 'http://www.oncf.ma', 'MESTOURI', 'hindmestouri@yahoo.fr', 'ingÃ©nieurs en RÃ©seaux et tÃ©lÃ©communications ', '06/12-11:56', 'Mme Meriem DAOUAH et M Driss MASSBAHI', 'massbahi.driss@gmail.com  , daouah.meriem@gmail.com ', '', '2015-02-23', '00:00:00'),
*(50, 'elfassihafsa', 'hafsa/1992', 'F', '45', '15,22', 'ELFASSI', '', '', 'Hafsa', '', '', '06 71 16 48 42 ', ' ', ' ', 'elfassi.hafsa@gmail.com', '', '', 'Casablanca', ' Mise en place d\'une plateforme de signature Ã©lectronique (Oxyliom e-sign)', '', '', 'pas dÃ©fini', '09/02/2015', '4 mois ou plus', 'Oxyliom', 'NÂ° 280,Technopark Casablanca\r\nhttp://oxyliom.com/', 'ATLAS', 'abdelghafour.atlas@gmail.com', '', '06/16-22:52', '', '', '', '2015-02-23', '00:00:00'),
(51, 'birjali', '#birjali#marouane#', 'T', '46', '15,50', 'BIRJALI', '', '', 'Marouane', '', '', '06 79 04 91 23 ', ' ', ' ', 'birjali.marouane@gmail.com', '', '', 'Casablanca', 'Mise en place dâ€™une nouvelle architecture Wi-Fi Outdoor de lâ€™opÃ©rateur INWI (INWI_WiFi7dak) : Etude, intÃ©gration des Ã©quipements, Design Radio et suivi des KPI', 'AprÃ¨s le succÃ¨s de lâ€™opÃ©ration pilote Ã  El Jadida, inwi annonce le lancement de la solution WiFi7dak Ã  Casablanca et, bientÃ´t, dans dâ€™autres villes du royaume.\r\nInwi confirme son leadership sur les solutions de connexions mobiles et lance Wifi7dak Ã  Casablanca. \r\nLâ€™opÃ©rateur global et alternatif des tÃ©lÃ©communications poursuit ainsi ses efforts dâ€™innovation technologique et commerciale pour dÃ©mocratiser lâ€™accÃ¨s Ã  Internet, pour tous et aux meilleurs conditions.\r\nFort du lancement rÃ©ussi de Wifi7dak Ã  El Jadida depuis juillet 2013, inwi dÃ©ploie ce service innovant dans quatre centres nÃ©vralgiques de la mÃ©tropole Ã©conomique Ã  savoir : Derb Ghallef, le Maarif, la Place des Nations Unies et la place Mohammed V. Les utilisateurs dâ€™ordinateurs portables, de tablettes ou de Smartphones pourront ainsi profiter dâ€™une connexion wifi haut dÃ©bit en plein air. \r\nMa mission consiste Ã  faire l\'Ã©tude, Design et le suivi des KPI de la nouvelle architecture Wi-Fi pour la ville de Casablanca ainsi de faire l\'intÃ©gration des diffÃ©rents Ã©quipements de cette solution.', 'WiFi Outdoor, WiFi Indoor, AC2000, SC700, AP, Atoll 3D, KPI, SIG, 3G, 4G, Radio FrÃ©quence, Design, AWMS, Backhaul Wireless, A8-Ei, A2, C1, CPE, â€¦', 'non', '02/03/2015', '4 mois', 'WANA Corporate (INWI) & Department of Radio Access Network ', 'Adresse : Lotissement La Colline II, lot. nÂ°1 et 2 Sidi MaÃ¢rouf Quartier: Sidi Maarouf CASABLANCA\r\nTel : 0529000000\r\nWeb : http://www.inwi.ma/\r\n', 'AMMAR', 'ab.ammar@yahoo.fr', 'Project Manager', '06/19-12:07', 'Youssef CHAHINE', 'youssef.chahine@inwi.ma', '', '2015-02-24', '00:00:00'),
(52, 'zineb', 'zineb', 'T', '47', '15,00', 'NADIFI', 'ELBESRAOUI', '', 'Zineb', 'Imane', '', '06 75 48 44 54 ', '06 44 16 56 56 ', ' ', 'zinebnadifi5@gmail.com', 'imane.elbesraoui@gmail.com', '', 'Casablanca ', 'integration de la 2G/3G via la transmission FH et FO dans le rÃ©seau Meditel', 'C\'est un projet que BTScom travaille en tant que sociÃ©tÃ© de service de Meditel, et qui consiste Ã  faire un swap du FH en FO et l\'Ã©tude de cas d\'une intÃ©gration d\'une BTS en utilisant la tÃ©chnologie FO dans le cadre du projet actuel: co-transmission dans le rÃ©seau Meditel.', 'fibre optique , faisceau hertzien', 'non', '01/03/2015', '3mois', 'BTScom ', 'adresse: lotissement Saadi, Lot 19 Bd Chefchaouni, Q.I Ain sbaa Casablanca\r\nweb: www.btscom.ma\r\ntel: +212522662994\r\nfax: +212522660942', 'JRAIFI', 'jraifi.abdelilah@gmail.com', 'IngÃ©nieure ', '06/08-01:49', 'Mouna Zerhouni', 'm.zerhouni@btscom.ma', '0669599379', '2015-02-24', '00:00:00'),
*(53, 'hajar', 'laila', 'F', '48', '14,65', 'EL  HADHADI', 'EZZRAIDY', '', 'Laila', 'Hajar', '', '06 76 58 44 89 ', '06 51 31 87 54 ', ' ', 'laila.elhadhadi@gmail.com', 'hajar.ezzraidy@gmail.com', '', 'Rabat', ' Etude, Conception et RÃ©alisation dâ€™un Module dâ€™IngÃ©nierie de Formation et d\'un autre de Gestion de Formation, Applicative au Projet SIRHUS. ', 'Notre  mission est lâ€™Ã©tude, la conception  et  la rÃ©alisation de deux modules destinÃ©s Ã  Ãªtre  intÃ©grÃ©s au projet SIRHUS , un pour lâ€™ingÃ©nierie de formation , qui a pour objet de  dÃ©finir  les particularitÃ©s  pratiques  de  la  constitution  du  plan  de formation  annuel  et  de  la dÃ©marche  Ã   suivre  dans  le  cadre  de  lâ€™ingÃ©nierie  de  formation,  lâ€™autre  pour  la    gestion    de formation  ,qui  a  pour  objet  de  dÃ©finir  les  modalitÃ©s  pratiques  de  gestion  et  de  rÃ©alisation  des \r\nactions de formation planifiÃ©es et non planifiÃ©es.  ', 'Groovy,Grails,Agile,Git,Trello,UML.', 'pas dÃ©fini', '09/02/2015', '6 mois ', 'Sofrecom Technopolis \r\nDÃ©partement IT ', 'Technopolis Rabat ', 'ECH-CHADI', 'saidech@gmail.com', 'Senior Software Engineer, avec diverses expÃ©riences en \r\nFinance, Gouvernement, Telecom, e-banking et Off-shoring chez SofrecomTechnopolis', '06/04-23:27', 'EL AOUFIR Mehdi ', 'melaoufir@gmail.com    /    mehdi.elaoufir@sofrecom.com', '  +212 (0) 5 37 27 79 17           ', '2015-02-24', '00:00:00'),
(54, 'Safae', 's@f@e', 'T', '49', '', 'ADERDOUR', '', '', 'Safae', '', '', '06 36 46 99 91 ', ' ', ' ', 'aderdour.safae@gmail.com', '', '', 'Toulouse', 'Contribution Ã  la conception dâ€™une couche de Transport autonome, orientÃ©e services et basÃ©e composants', '', 'Couche transport, UML, SOA, CBA, XML, Anthologies, Automates Ã  Ã©tat fini, thÃ©orie dÃ©cisionnelle.', 'non', '1 Mars ', '6 mois', 'LAAS du CNRS dans lâ€™Ã©quipe SARA(Services et Architectures pour les RÃ©seaux AvancÃ©s)', 'CNRS DR14, 16 avenue Edourd Belin BP 24367, 31055 Toulouse Cedex 4\r\nhttps://www.laas.fr/public/', 'ZYANE', 'a.zyane@yahoo.fr', 'Professeur Ã  lâ€™INSA de Toulouse DÃ©partement GÃ©nie Ã‰lectrique et Informatique. Chercheur au LAAS du CNRS, Ã©quipe SARA', '06/15-15:36', 'Christophe CHASSOT', 'christophe.chassot@insa-toulouse.fr', '(33) (0)5 61 55 98 00', '2015-02-24', '00:00:00'),
*(55, 'ElMortajiRim', '123456789', 'F', '50', '13,85', 'EL MORTAJI', '', '', 'Rim', '', '', '06 61 07 58 21 ', ' ', ' ', 'rim.elmortaji5@gmail.com', '', '', 'Casablanca', '  Mise en place dâ€™une solution workflow dâ€™automatisation du circuit de validation des factures au sein de la Royal Air Maroc', 'Il s\'agit de dÃ©velopper une chaine de validation \"workflow\", pour pouvoir automatiser le processus de traitement des factures reÃ§ues de la RAM tout en fournissant aux responsables un outil de suivi qui permet de tracer toutes les informations provenant du processus, mais aussi de dÃ©tecter des Ã©ventuels retards de validation et/ou de contrÃ´le.', 'workflow,suivi,facture', 'oui', '1/2/2015', '6mois', 'SiÃ¨ge de la Royal air Maroc\r\n\r\ndÃ©partement SI', 'Moulay Abdellah Cherif, Casablanca, Maroc', 'ECH-CHADI', 'saidech@gmail.com', 'Chef du service', '05/30-18:37', 'JIBAR HASSAN', 'HJIBAR@royalairmaroc.com', '', '2015-02-24', '00:00:00'),
*(56, 'FatimaZahraeTahiriSahra', 'fatigirl', 'F', '51', '14,72', 'TAHIRI SAHRA', '', '', 'Fatima zahrae', '', '', '06 22 19 63 89 ', ' ', ' ', 'fati.tahiri.sahra@gmail.com', '', '', 'CasaBlanca', 'Automatisation des procÃ©dures internes de lâ€™entreprise via un BPM et le dÃ©veloppement dâ€™un module complÃ©mentaire', 'Ce projet de fin d\'Ã©tudes vise Ã  automatiser les diffÃ©rents processus mÃ©tier de l\'entreprise JACOBS ENGINEERING SA(siÃ¨ge) et ce Ã  l\'aide d\'un outil de gestion des processus mÃ©tier(Business Process Managment-BPM). L\'outil toutefois reprÃ©sente des restrictions en terme de fonctionnalitÃ©s offertes, ce qui nÃ©cessite le dÃ©veloppement de modules complÃ©mentaires selon le besoin. Le besoin de l\'entreprise pour une gestion personnalisÃ©e des processus et des groupes de l\'entreprise nÃ©cessite le dÃ©veloppement d\'un plugin. ', 'BPM-Process Maker-ExtJS- Gulliver Framework-PHP5-Ajax ', 'pas dÃ©fini', '23/02/2015', '4 mois', 'Jacobs Engineering SA', 'Imm NÂ°5, Zenith Millenium, Lot Attoufik, Route de Nouaceur Sidi MÃ¢arouf, Casablanca | www.jacobs.com', 'OUAFIK', 'youafik@yahoo.fr', 'IngÃ©nieur Ã©tudes et dÃ©veloppement', '06/08-21:26', 'EL ASSAMI Ilyass', 'ilyass.elassami@jacobs-esa.com', '', '2015-02-24', '00:00:00'),
(57, 'JERNANE', 'ensas2015', 'T', '52', '15,20', 'JERNANE', '', '', 'Mehdi', '', '', '06 07 65 96 77 ', ' ', ' ', 'mehdi.jernane@gmail.com', '', '', 'Marrakech', 'supervision et sÃ©curitÃ©', 'Supervision des pÃ©riphÃ©riques du rÃ©seau interne de l\'hÃ´tel  et proposÃ© une sÃ©curitÃ© (authentification) pour accÃ©der a distance au pÃ©riphÃ©rique Cisco. ', 'supervision(Cacti,NAGIOS...),sÃ©curitÃ© des ports(802.1X),cisco,serveurs(Opera,Active Directory,HQ,FreeRadius...),Voip(tÃ©lÃ©phone IP),RADIUS', 'pas dÃ©fini', '24/02/2005', '4 mois', 'palmeraie Holding , dÃ©partement System informatique', 'www.pgpmarrakech.com', 'CHAHIN', 'radouane.chahin@gmail.com', 'IngÃ©nieure en System rÃ©seau', '06/14-14:54', 'Mlle Mouna', 'm.elourf@palmeraieresorts.com', '0660113082', '2015-02-24', '00:00:00'),
(58, 'N.Yassmine', '0524626849', 'T', '53', '15,50', 'NADIR', '', '', 'Yassmine', '', '', '06 55 27 46 87 ', ' ', ' ', 'nadir.yassmine@gmail.com', '', '', 'Casablanca', 'Mise en place des solutions de sÃ©curisation des rÃ©seaux LAN et WAN de l\'entreprise', '', '', 'non', '16/02/2015', '4 mois', 'La Voie Express\r\ndÃ©partement des systÃ¨mes d\'information', 'http://www.lavoieexpress.ma/', 'MADIAFI', 'madiafi.med@gmail.com', 'responsable des Systemes et reseaux', '05/07-11:26', 'Fouad Maziani', 'f.maziani@lavoieexpress.ma', '', '2015-02-24', '00:00:00'),
(59, 'Youssfi.Merroche', 'y1990m1992', 'T', '54', '16,00', 'YOUSSFI', 'MERROCHE', '', 'Soukaina', 'Maryem', '', '06 45 46 55 16 ', '06 98 97 29 55 ', ' ', 'youssfi.soukaina@gmail.com', 'maryemmerroche@gmail.com', '', 'casablanca', 'planification et optimisation des reseaux cellulaires 2G  et 3G', '', 'planification,optimisation,2G,3G,genex,attol,U-net.', 'pas dÃ©fini', '23/02/2015', '4 mois', 'Hwawei', '', 'BARAKA', 'baraka.kamal@yahoo.fr', 'manager', '06/16-23:58', 'Ahmed Arizki', 'AHMED.ARIZKI@huawei.com', '0600010043', '2015-02-24', '00:00:00'),
(60, 'mouttakisara', 'veerzara', 'T', '55', '15,50', 'MOUTTAKI', '', '', 'Sara', '', '', '06 41 08 82 07 ', ' ', ' ', 'mouttaki.sara@gmail.com', '', '', 'Casablanca', 'Optimisation du rÃ©seau LTE (4G) MEDITEL', '', '', 'pas dÃ©fini', '16/02/2015', '4 mois', 'Huawei Technologies', '', 'MADIAFI', 'madiafi.med@gmail.com', 'Project Manager du projet LTE', '06/04-17:14', 'EL OUROUBA Soufiane', '', '', '2015-02-24', '00:00:00'),
*(61, 'siham', '0657571050ENSA', 'F', '56', '14,88', 'MOUSSAMIR', '', '', 'Siham', '', '', '06 57 57 10 50 ', ' ', ' ', 'siham.moussamir@gmail.com', '', '', 'RABAT', 'Refonte et Ã©volution de la solution SafeEDI (IS + IR) et la mise en place d\'une usine logicielle', 'SAFE EDI Fiscal est un outil pour la gÃ©nÃ©ration des dÃ©clarations fiscales en mode EDI (Echange de DonnÃ©es InformatisÃ©) conÃ§u spÃ©cialement pour rÃ©pondre aux besoins des entreprises marocaines dÃ©sirantes effectuer leurs dÃ©clarations IS , IR ou TVA en toute simplicitÃ© auprÃ¨s de la Direction GÃ©nÃ©rale des ImpÃ´ts.', 'Struts2, Spring ioc, JPA, Bootstrap3, tomcat, eclipse kepler, mysql, Hudson, Sonar, Mantis, Jira ...', 'pas dÃ©fini', '03/02/2015', '6 mois', 'SafeDEMAT SARL', '33, Avenue Ibn Sina Appt NÂ°43 Agdal - RABAT', 'OUAFIK', 'youafik@yahoo.fr', 'responsable technique', '06/04-13:52', 'El Houssain BEN MESSAOUD', 'hbenmessaoud@yahoo.fr', '06 68 70 51 08', '2015-02-25', '00:00:00'),
*(62, 'Sarra', '396951', 'F', '57', '16,00', 'ENNAJI', '', '', 'Sarra', '', '', '06 59 74 70 60 ', ' ', ' ', 'sarra.ennaji@gmail.com', '', '', 'Rabat', 'Automatisation des tests (fonctionnels) pour deux modules d\'un SI (Projet SIRHUS)', '', '', 'pas dÃ©fini', '19 FÃ©vrier 2015', '', 'SOFRECOM', '', 'BOUARIFI', 'walid.bouarifi@gmail.com', 'Project Manager', '06/13-08:21', 'Mehdi Elaoufir', '', '', '2015-02-25', '00:00:00'),
*(63, 'Elgardid', '123A', 'F', '58', '15,11', 'EL GARDID', '', '', 'Akram', '', '', '06 53 92 13 16 ', ' ', ' ', 'akram.elgardid@gmail.com', '', '', 'Casablanca.', 'RÃ©alisation dâ€™une solution intranet de travail collaboratif et mise en place de Workflows.', '', '', 'pas dÃ©fini', '', '', 'AMADEUS Maroc.', 'http://www.amadeus.com', 'BOUARIFI', 'walid.bouarifi@gmail.com', '', '06/18-16:50', 'Zouhair RIMALE', '', '', '2015-02-25', '00:00:00'),
*(64, 'Omar.Sdaq', 'cb3db40eAFF', 'F', '59', '14,50', 'SDAQ', '', '', 'Omar', '', '', '06 75 32 04 09 ', ' ', ' ', 'omar.sdaq@gmail.com', '', '', 'Rabat', 'Mise en place d\'une solution de gestion d\'enquÃªte et des collectes d\'informations.', 'Ce projet comportera une application mobile qui permettra de collecter les donnÃ©es ainsi qu\'une plateforme desktop qui s\'occupera de crÃ©er les enquÃªte, en plus de les classer et d\'exploiter leur donnÃ©es.', 'Android,.Net,Mobile..', 'pas dÃ©fini', '16/02/2015', '4 mois', 'Novec', '', 'BOUARIFI', 'walid.bouarifi@gmail.com', '', '06/29-13:27', '', '', '', '2015-02-25', '00:00:00'),
(65, 'hind.ghaloua', 'anrtpfe', 'T', '60', '15,50', 'GHALOUA', 'BENTOUMI', '', 'Hind', 'Soukaina', '', '06 99 72 98 54 ', '06 74 70 73 31 ', ' ', 'hind.ghaloua@gmail.com', 'bentoumi.soukaina3@gmail.com', '', 'rabat', 'Mise en place d\'un systÃ¨me de mesure de dÃ©bit internet au niveau des Ã©tablissements scolaires Ã  distance', '', '', 'pas dÃ©fini', '', '', '', '', 'BABALAHCEN', 'babalahcenrajaa@yahoo.fr', '', '06/15-15:35', '', '', '', '2015-02-25', '00:00:00'),
(66, 'rhilmane', '123.@', 'T', '61', '14,50', 'RHILMANE', '', '', 'Hajar', '', '', '06 17 88 02 15 ', ' ', ' ', 'h.rhilmane@gmail.com', '', '', 'lÃ ayoune', 'optimisation de l\'exploitation du rÃ©seau de telecommunication interne', '-DÃ©finition des besoins de l\'entreprise en termes d\'infrastructures et d\'Ã©quipements de tÃ©lÃ©communication.\r\n-Etude critique de l\'existant.\r\n-Proposition d\'une amÃ©lioration.', 'SDH, PDH, Fibre optique, Faisceau hertzien, D-WDM, STM-n', 'pas dÃ©fini', '19/02/2015', '4 mois', 'Entreprise:OCP lÃ ayoune,DÃ©partement:tÃ©lÃ©communication.', '', 'MESTOURI', 'hindmestouri@yahoo.fr', 'Responsable maintenance,Ã©nergie et eau Ã  PHOSBOUCRAA', '06/14-23:38', 'Brahim OUAHLI', 'b.ouahli@ocpgroup.ma', '0528999339/0661287419', '2015-02-27', '00:00:00'),
(67, 'TABIAT', 'ALLAHKARIM', 'T', '62', '15,60', 'TABIAT', '', '', 'Chorouk', '', '', '06 65 43 38 82 ', ' ', ' ', 'chorouktabiat@gmail.com', '', '', 'Casablanca', 'Ã‰tude de la solution MSAN dans le rÃ©seau fixe de MAROC TELECOM: DÃ©ploiement, Migration et Ã©laboration d\'une application Java pour automatiser l\'intÃ©gration', '', 'MSAN,RTC,NGN,NMS', 'pas dÃ©fini', '01/03/2015', '5 mois', 'ZTE Corporation MAROC', ' Lot EL Affak imm 449-450 Sigma 3Ã¨me Ã©tage La Colline Sidi Maarouf Casablanca MAROC', 'MESTOURI', 'hindmestouri@yahoo.fr', 'Chef de projet rÃ©gional', '04/21-00:23', 'BENSASSI Mohamed', 'bensassi87@gmail.com', '0522321408/0661901147', '2015-02-27', '00:00:00'),
(68, 'aboumada', 'ouarzazate', 'T', '63', '14,50', 'ABOUMADA', '', '', 'Hassan', '', '', '06 71 57 57 81 ', ' ', ' ', 'aboumada.hassan@gmail.com', '', '', 'Casablanca', 'Etude de la migration dâ€™ATM vers lâ€™IP RAN', '', 'IP/MPLS, BGP ,ISIS, VPN-L2, VPN-L3', 'pas dÃ©fini', '03/03/2015', '31/05/2015', ' Huawei Technologies / Datacom', 'Sidi Maarouf', 'MADIAFI', 'madiafi.med@gmail.com', 'ingÃ©nieur  dans  le  dÃ©partement Datacom ', '06/02-18:19', 'HARRAK Yasser', 'harrak.yasser@huawei.com', '', '2015-02-27', '00:00:00'),
*(70, 'Arfaoui', '123456789', 'F', '65', '15,70', 'ARFAOUI', '', '', 'Nouaman', '', '', '06 52 61 88 08 ', ' ', ' ', 'nouaman.arfaoui@gmail.com', '', '', 'Rabat', 'Authentification dÃ©lÃ©guÃ©e sous wakanda (IntÃ©gration de Facebook Login/Signup,Twitter,Google...)', '', '', 'pas dÃ©fini', '23/02/2015', '4 mois', '4D', 'www.4d.com/fr/', 'ELBOUSTANI', 'hakim.el-boustani@orange.fr', 'IngÃ©nieur dÃ©veloppeur javaScript ', '05/31-00:26', 'MESAOUDI MOHAMMED', 'mmesaoudi@4d.com', '0642488524', '2015-03-01', '00:00:00'),
(71, 'tahaettabaa', 'taha09', 'T', '66', '15,00', 'ETTABAA', '', '', 'Taha ', '', '', '06 22 27 46 06 ', ' ', ' ', 't.ettabaa@gmail.com', '', '', 'Casablanca', ' la mise en place dâ€™une architecture IPv6 ', '-Effectuer une Ã©tude thÃ©orique approfondie autour du protocole IPv6, permettant de bien connaitre le sujet\r\n\r\n-Rentrer dans le dÃ©tail des Ã©quipements IP qui sont installÃ©s aujourdâ€™hui, et vÃ©rifier sâ€™ils supportent ou non lâ€™IPv6\r\n\r\n-PrÃ©parer un design pour la mise en place dâ€™une architecture IPv6 dans le Lab\r\n\r\n-Effectuer un test rÃ©el de navigation IPv6', '', 'pas dÃ©fini', '', '', 'INWI ', '', 'OUARRACHI', 'maryam.ouarrachi@gmail.com', 'chef de projet ', '05/27-13:18', 'Ziad sarhani', '', '', '2015-03-01', '00:00:00'),
(72, 'khadija', 'M@rouane1998', 'T', '67', '', 'AZIZ', '', '', 'Khadija', '', '', '06 74 89 95 24 ', ' ', ' ', 'khadija.aziz.10@gmail.com', '', '', 'Casablanca', 'Mise en place d\'une solution de supervision rÃ©seau ', '', '', 'pas dÃ©fini', '', '', 'ZEN NETWORKS', '', 'BENLAMKADEM', 'benlamkadem@gmail.com', '', '06/02-17:46', 'FayÃ§al NOUSHI', 'faycal.noushi@gmail.com', '+212661560337', '2015-03-01', '00:00:00'),
(73, 'DAOUIRI', 'amounalmaziouna', 'T', '68', '15,00', 'DAOUIRI', '', '', 'Imane', '', '', '06 97 43 81 63 ', ' ', ' ', 'daouiri.i@gmail.com', '', '', 'Rabat', 'Plannification et Optimisation Radio WCDMA d\'une plaque ', 'Ce projet de fin dâ€™Ã©tudes est au sein du dÃ©partement RNP (Radio Network Planning). \r\n-MaÃ®triser les concepts dâ€™optimisation Radio WCDMA et les mettre en pratique.', 'Optimisation, drive test , KPI', 'pas dÃ©fini', '15 FÃ©vrier ', '4 mois', 'HUAWEI', 'Av. Annakhil , Imm. Hight tech, Hay Riad. Rabat', 'MESTOURI', 'hindmestouri@yahoo.fr', 'IngÃ©nieur optimisation Radio', '06/06-13:33', 'El-Hussein Hegazy', 'hussein.hegazy@yahoo.com', '0661408995', '2015-03-02', '00:00:00');
INSERT INTO `ensas_pfe` (`id`, `username`, `password`, `filiere`, `groupe`, `note`, `nom1`, `nom2`, `nom3`, `prenom1`, `prenom2`, `prenom3`, `GSM1`, `GSM2`, `GSM3`, `email1`, `email2`, `email3`, `ville`, `sujet`, `descr`, `motscle`, `preembauche`, `debut`, `duree`, `entreprise`, `adresse`, `encadrant`, `email_encadrant`, `fonction`, `dateconsult`, `encadrant_ext`, `email_encadrant_ext`, `GSM_encadrant_ext`, `date`, `heure`) VALUES
(74, 'Ourchid', '1990', 'T', '69', '14,34', 'OURCHID', '', '', 'Mohamed', '', '', '06 68 20 24 59 ', ' ', ' ', 'mohamed.ourchid@gmail.com', '', '', 'Casablanca', 'Construction d\'un site mobile - gÃ©nie civil, installation MES et intÃ©gration du site via liaison en fibre optique- ', ' Construction d\'un site mobile - gÃ©nie civil, installation MES et intÃ©gration du site via liaison en fibre optique- ', '', 'pas dÃ©fini', '16 mars', '', 'CEGELEC\r\nGRANIOU MAROC', '126, Bd Oqba bnou nafia, 20351 Casablanca - MAROC', 'AMMAR', 'ab.ammar@yahoo.fr', 'IngÃ©nieur Travaux\r\nGRANIOU MAROC', '06/10-23:18', 'Mohamed Chikhi', 'mohamed.chikhi@graniou.com ', '+212 6 61 79 21 35', '2015-03-02', '00:00:00'),
*(75, 'haddouch.khalil', 'khalil06', 'F', '70', '15,03', 'HADDOUCH', '', '', 'Mohammed khalil', '', '', '06 43 60 10 49 ', ' ', ' ', 'haddouch.khalil@gmail.com', '', '', 'Casablanca', 'Evolution et maintien en condition opÃ©rationnelle des applications CRM du client GDF Suez.', '', '', 'pas dÃ©fini', '16/03/2015', '6 mois', 'CGI Technologies et Solution Maroc SAS', '', 'BOUARIFI', 'walid.bouarifi@gmail.com', '', '05/15-17:09', 'Saad BELHADI', '', '', '2015-03-04', '00:00:00'),
*(76, 'soufianesakhi', '123456', 'F', '71', '15,50', 'SAKHI', '', '', 'Soufiane', '', '', '06 02 40 70 21 ', ' ', ' ', 'sakhi.soufiane@gmail.com', '', '', 'Eljadida', 'Application mobile de networking professionnel', 'Creation d\'une application mobile de networking.', 'networking, android, ios', 'non', '26 janvier 2015', '6 mois', 'Fundadors Group', 'www.linkry.co', 'ATLAS', 'abdelghafour.atlas@gmail.com', 'CEO', '04/20-11:46', 'Ahmed Zrikem', '', '', '2015-03-05', '00:00:00'),
(77, 'hnakiri', 'Support2424', 'F', '72', '15,85', 'NAKIRI', '', '', 'Hajar', '', '', '06 43 48 76 59 ', ' ', ' ', 'hajar.nakiri@gmail.com', '', '', 'Casablanca', 'Mise en place dâ€™un outil de gestion des commandes erronÃ©es  (Projet : Horizon-essilor )', '', 'asp.net', 'oui', '23/02/2015', '6', 'Capgemini Casablanca', 'www.capgemini.com', 'LAKHEL', 'lakhel@yahoo.fr,lakhel@ucam.ac.ma', '', '06/06-15:27', 'Aboudar Yassine', 'yassine.aboudar@capgemini.com', '', '2015-03-05', '00:00:00'),
(78, 'GROLA', 'azertyaa', 'F', '73', '15,57', 'GROLA', '', '', 'Rihame', '', '', '06 74 07 38 98 ', ' ', ' ', 'grola.rihame@gmail.com', '', '', 'Casablanca', 'Evolution et maintien en condition opÃ©rationnelle des applications CRM du client GDF Suez', '', 'CRM', 'pas dÃ©fini', '16/03/2015', '6 mois', 'CGI Technologies et Solutions Maroc SAS ', ' Nearshore Park 1100 Boulevard AL QODS\r\n\r\nShore 2 (201 et 202) Shore 5 (201 et 202) | Sidi Maarouf\r\n\r\nCasablanca | Maroc', 'LAKHEL', 'lakhel@yahoo.fr,lakhel@ucam.ac.ma', '', '06/11-15:38', 'Saad Belhadi', '', '0529045450', '2015-03-05', '00:00:00'),
(79, 'sedratychaimae', 'Chaimae.290792++', 'T', '74', '', 'SEDRATY ', '', '', 'Chaimae', '', '', '06 30 90 53 25 ', ' ', ' ', 'sedraty.chaimae@gmail.com', '', '', 'Casablanca', 'planification et optimisation du rÃ©seaux 3G au profit de INWI', '', '3G, UMTS,optimisation, planification, dÃ©ploiement ', 'pas dÃ©fini', '09/03/2015', '3mois minimum ', 'Huawei Technologies Morocco sar\r\ndepartement 3G inwi', '37 lotissement la colline 2 lotissement la colline 2 CASABLANCA', 'BENLAMKADEM', 'benlamkadem@gmail.com', 'RNP-RNO Engineer', '06/08-02:31', 'zakaria DARRAG', 'zakaria.darrag@huawei.com', '0522785400', '2015-03-05', '00:00:00'),
//(80, 'azizsalma', 'salmasalma', 'T', '75', '14,70', 'AZIZ', '', '', 'Salma', '', '', '06 71 72 56 24 ', ' ', ' ', 'azizsalma66@gmail.com', '', '', 'casablanca', 'ImplÃ©mentation de la plateforme de sÃ©curitÃ© informatique au niveau de lâ€™ONP ', 'ImplÃ©mentation de la plateforme de sÃ©curitÃ© informatique au niveau de lâ€™ONP et dâ€™administration de ces Ã©quipements : basÃ©e au niveau du siÃ¨ge social autour de firewalls UTM en deux niveaux (FG-300D-BDL et ASA 5525-IPS), solution de contrÃ´le dâ€™admission et de conformitÃ© au rÃ©seau LAN de lâ€™ONP (ISE : Cisco SNS 3415), plateforme de couverture WIFI (Points dâ€™accÃ¨s et contrÃ´leur Wifi) et des firewall en un seul niveau pour les sites distants', '', 'non', '21 Fevrier', '3 mois', 'Office Nationale de peche', '', 'HEDABOU', 'mhedabou@yahoo.fr', 'Chef de division infrastructure et rÃ©seaux', '03/12-23:48', 'LABZAOUI Bouchaib', 'B.Labzaoui@onp.ma', ' 06 19 000 879', '2015-03-05', '00:00:00'),
//(118, 'ILeralla', 'leralla@ ', 'T', '76', '14,50', 'LERALLA', '', '', 'Ihssane', '', '', '06 49 33 96 23 ', '06 91 59 36 60 ', ' ', 'ihssane.leralla@gmail.com', '', '', 'Rabat', 'Etude et Mise en place d\'une solution sÃ©curitÃ© rÃ©seau UTM destinÃ©e au HCEFLCD', '', '', 'pas dÃ©fini', '', '', ' Neurones Technologies - Rabat', '', 'BABALAHCEN', 'babalahcenrajaa@yahoo.fr', 'IngÃ©nieur rÃ©seau et Telecommunication', '06/13-18:21', 'Mahmoudi Ayoub', 'mahmoudi@neurones.ma', '+212642998617', '2015-03-12', '00:00:00');

-- --------------------------------------------------------

--
-- Structure de la table `ensas_pfe_options`
--

CREATE TABLE `ensas_pfe_options` (
  `id` int(11) NOT NULL,
  `label` varchar(255) DEFAULT NULL,
  `valeur` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `ensas_pfe_options`
--

INSERT INTO `ensas_pfe_options` (`id`, `label`, `valeur`) VALUES
(2, 'prof_attrib_valide', 'valide');

-- --------------------------------------------------------

--
-- Structure de la table `ensas_pfe_profs`
--

CREATE TABLE `ensas_pfe_profs` (
  `id` int(10) UNSIGNED NOT NULL,
  `nom` varchar(64) NOT NULL,
  `prenom` varchar(64) NOT NULL,
  `email` varchar(128) NOT NULL,
  `GSM` varchar(64) NOT NULL,
  `jury` varchar(4) NOT NULL,
  `salle` varchar(64) NOT NULL,
  `observations` varchar(128) NOT NULL,
  `specialite` varchar(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `ensas_pfe_profs`
--

INSERT INTO `ensas_pfe_profs` (`id`, `nom`, `prenom`, `email`, `GSM`, `jury`, `salle`, `observations`, `specialite`) VALUES
(1, 'ECH-CHADI', 'Said', 'saidech@gmail.com', ' ', '4', '', '', ''),
(2, 'HEDABOU', 'Mustapha', 'mhedabou@yahoo.fr', ' ', '1', '', '', ''),
(4, 'ATLAS', 'Abdelghafour', 'abdelghafour.atlas@gmail.com', '06 61 72 19 80 ', '6', '', '', ''),
(5, 'BOUARIFI', 'Walid', 'walid.bouarifi@gmail.com', '06 62 13 89 33 ', '6', '', '', ''),
(6, 'ZYANE', 'Abdellah', 'a.zyane@yahoo.fr', ' ', '2', '', '', ''),
(7, 'MESTOURI', 'Hind', 'hindmestouri@yahoo.fr', ' ', '3', '', '', ''),
(8, 'BENLAMKADEM', 'Abdellatif', 'benlamkadem@gmail.com', '06 66 41 00 34 ', '2', '', '', ''),
(9, 'OUAFIK', 'Youssef', 'youafik@yahoo.fr', ' ', '4', '', '', ''),
(10, 'BERAMDAN', 'Loubna', 'loubnaberamdan@gmail.com', '06 63 29 68 25 ', '', '', '', ''),
(11, 'OUARRACHI', 'Meryam', 'maryam.ouarrachi@gmail.com', ' ', '4', '', '', ''),
(12, 'CHAHIN', 'Redoine', 'radouane.chahin@gmail.com', '06 99 93 03 65 ', '5', '', '', ''),
(13, 'LAKHEL', 'Hassan', 'lakhel@yahoo.fr,lakhel@ucam.ac.ma', ' ', '1', '', '', ''),
(14, 'ELBOUSTANI', 'Hakim', 'hakim.el-boustani@orange.fr', ' ', '5', '', '', ''),
(15, 'MABTOUL', 'Samira', 'mabtoul_samira@yahoo.fr', ' ', '1', '', '', ''),
(16, 'BARAKA', 'Kamal', 'baraka.kamal@yahoo.fr', ' ', '2', '', '', ''),
(17, 'MADIAFI', 'Mohamed', 'madiafi.med@gmail.com', ' ', '3', '', '', ''),
(18, 'JRAIFI', 'Abdelilah', 'jraifi.abdelilah@gmail.com', ' ', '6', '', '', ''),
(19, 'BABALAHCEN', 'Rajaa', 'babalahcenrajaa@yahoo.fr', ' ', '3', '', '', ''),
(20, 'AMMAR', 'Abdelghali', 'ab.ammar@yahoo.fr', ' ', '5', '', '', '');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `ensas_pfe`
--
ALTER TABLE `ensas_pfe`
  ADD UNIQUE KEY `id_2` (`id`),
  ADD KEY `id` (`id`);

--
-- Index pour la table `ensas_pfe_options`
--
ALTER TABLE `ensas_pfe_options`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `label` (`label`);

--
-- Index pour la table `ensas_pfe_profs`
--
ALTER TABLE `ensas_pfe_profs`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `ensas_pfe`
--
ALTER TABLE `ensas_pfe`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=119;

--
-- AUTO_INCREMENT pour la table `ensas_pfe_options`
--
ALTER TABLE `ensas_pfe_options`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT pour la table `ensas_pfe_profs`
--
ALTER TABLE `ensas_pfe_profs`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
